cpu-bind=MASK - bp1-compute031, task 4294967295 4294967295 [0]: mask 0x800000800 set
/user/home/of15641/.conda/envs/openmm/bin/python
../LHII_MD/output/1ps_2fs.dcd
../LHII_MD/LH2.prmtop
Finished 'load_dcd_file' in 7.871786 secs

Error: SCF not converged after 511 cycles

Error: SCF not converged after 511 cycles

Error: SCF not converged after 511 cycles
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/user/home/of15641/.conda/envs/openmm/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/user/home/of15641/.conda/envs/openmm/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "chl_xtb.py", line 83, in run_single_chl
    res = run_qcore(single_chl_str)
  File "chl_xtb.py", line 41, in run_qcore
    json_results = json.loads(json_run.stdout)
  File "/user/home/of15641/.conda/envs/openmm/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/user/home/of15641/.conda/envs/openmm/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/user/home/of15641/.conda/envs/openmm/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chl_xtb.py", line 129, in <module>
    run_trajectory("../LHII_MD/output/1ps_2fs_LHII.dcd", "../LHII_MD/LH2.prmtop", [0])
  File "chl_xtb.py", line 16, in wrapper_timer
    value = func(*args, **kwargs)
  File "chl_xtb.py", line 101, in run_trajectory
    frame_energies = p.map(run_single_chl, frame)      
  File "/user/home/of15641/.conda/envs/openmm/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/user/home/of15641/.conda/envs/openmm/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
